### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by ghost** [failury/react-auto-scroll-container#1]
Great component, but I'm receiving a failed to parse source map error where there is no such file or directory. Everything works, I'm just getting the error in the terminal. 

The complete error is 
WARNING in ./node_modules/react-auto-scroll-container/dist/esm/components/react-auto-scroll-container.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\user\test_application\frontend\node_modules\react-auto-scroll-container\src\components\react-auto-scroll-container.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\user\test_application\frontend\node_modules\react-auto-scroll-container\src\components\react-auto-scroll-container.tsx'

**Comment by failury** [comment]
Hi dahabibi, I have turned off the soucemap, can you try reinstalling the package to see if the error still persist.

**Comment by ghost** [comment]
The error does still persist unfortunately.

**Comment by failury** [comment]
I believe this is webpacks problem, can you try the solution in this link [https://stackoverflow.com/questions/74688133/how-can-i-fix-the-failed-to-parse-source-map-from-errors-in-my-reactjs-ts]()
